name: nuwats
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - axial-positional-embedding==0.3.12
      - beautifulsoup4==4.14.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colt5-attention==0.11.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - gdown==5.2.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - hyper-connections==0.2.1
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - local-attention==1.11.2
      - markupsafe==3.0.3
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - narwhals==2.10.2
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==1.5.3
      - patool==1.15.0
      - pillow==11.3.0
      - plotly==6.4.0
      - product-key-memory==0.2.11
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.36.2
      - reformer-pytorch==1.4.4
      - regex==2025.10.22
      - requests==2.32.5
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.10.1
      - six==1.17.0
      - soupsieve==2.8
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - timm==1.0.21
      - tokenizers==0.13.3
      - torch==2.8.0
      - torchcde==0.2.5
      - torchdiffeq==0.2.5
      - torchsde==0.2.6
      - torchvision==0.23.0
      - tqdm==4.67.1
      - trampoline==0.1.2
      - transformers==4.30.2
      - triton==3.4.0
      - typing-extensions==4.15.0
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - vl-convert-python==1.8.0
      - zipp==3.23.0
prefix: /mnt/4T/home/liwei/anaconda3/anaconda3/envs/nuwats
